# Generated by Django 5.2.7 on 2025-10-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationuuid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=500, null=True)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('favicon', models.URLField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('station_type', models.CharField(blank=True, choices=[('fm', 'FM'), ('web', 'Web'), ('dab', 'DAB'), ('am', 'AM'), ('satellite', 'Satellite'), ('other', 'Other')], max_length=30)),
                ('show_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('account_owner', models.CharField(blank=True, max_length=255)),
                ('last_contact_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
