# Generated by Django 5.2.5 on 2025-08-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=64, unique=True)),
                ('url', models.URLField()),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_url', models.URLField(blank=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='idle', max_length=50)),
                ('stop_requested', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('spotify_id', models.CharField(max_length=64, unique=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='État')),
                ('added_on', models.DateField(blank=True, null=True, verbose_name="Date d'ajout")),
                ('updated_on', models.DateField(blank=True, null=True, verbose_name='Mise à jour')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.track')),
            ],
            options={
                'unique_together': {('track', 'playlist')},
            },
        ),
    ]
