# Generated by Django 5.2.7 on 2025-10-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('spotify_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_url', models.URLField(blank=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('snapshot_id', models.CharField(blank=True, max_length=128, null=True)),
                ('discovered_on', models.DateTimeField(blank=True, null=True)),
                ('last_discovered', models.DateTimeField(blank=True, null=True)),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('redirect_uri', models.URLField(blank=True, default='http://127.0.0.1:8000/spotify/callback')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='idle', max_length=50)),
                ('stop_requested', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('extra_json', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracker.artist')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItemsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=128)),
                ('track_ids', models.JSONField(default=list)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_caches', to='tracker.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'snapshot_id')},
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(default='new', max_length=50)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='tracker.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='tracker.track')),
            ],
            options={
                'unique_together': {('track', 'playlist')},
            },
        ),
    ]
