# Generated by Django 5.2.7 on 2025-10-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('spotify_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('spotify_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=200, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('redirect_uri', models.URLField(blank=True, default='http://127.0.0.1:8000/spotify/callback')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='discovered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='last_discovered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='last_scanned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='snapshot_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='extra_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='tracker.playlist'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='state',
            field=models.CharField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='tracker.track'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='spotify_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='tracker.artist'),
        ),
        migrations.CreateModel(
            name='PlaylistItemsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=128)),
                ('track_ids', models.JSONField(default=list)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_caches', to='tracker.playlist')),
            ],
            options={
                'unique_together': {('playlist', 'snapshot_id')},
            },
        ),
    ]
